### ISSUE TITLE
Ticker Alert

### ISSUE THREAD

**Issue by gimmeyoon** [gimmeyoon/calerter#3]
## TODO

* Ticker Alert 하려면 시세를 real-time으로 받아와야함
  *  websocket에서 stream
  * single thread로 가기 위해 telegram -> aiogram
* Alert를 원하는 user의 chat id 기록

**Comment by gimmeyoon** [comment]
- [ ] from telegram to aiogram
- [ ] ticker stream receiver
- [ ] manage watchers
- [ ] change `get_price` from REST to stream

**Comment by gimmeyoon** [comment]
## from telegram to aiogram

* 미래의 확장성을 고려하여 aiogram으로 바꿈

## pr

https://github.com/gimmeyoon/calerter/pull/10

**Comment by gimmeyoon** [comment]
##  ticker stream receiver & manage watchers

* websocket으로 구현
* single thread & single event loop
  * event loop 는 alerter꺼 사용
  * 따라서 alerter에서 exchange의 coroutine을 호출해줌
  * alerter가 exchange를 관리하는 구조로 바꿈
* watchers
  * 지금은 ticker를 받아오기만하니까 watcher 관리할 필요없음
  * 추후에  watcher마다 다르게 행동해야할 때 별도의 이슈에서 다룸

## pr

https://github.com/gimmeyoon/calerter/pull/11
